services:

  weblogic_volume_init:
    image: container-registry.oracle.com/middleware/weblogic:14.1.1.0-11
    user: root
    command: >
      bash -c "chown -R 1000:0 /u01/oracle/user_projects/domains"
    volumes:
      - weblogic_hospital_auth_data:/u01/oracle/user_projects/domains

  weblogic:
    image: container-registry.oracle.com/middleware/weblogic:14.1.1.0-11

    container_name: weblogic-hospital-auth-server

    ports:
      - "7001:7001"
      - "9002:9002"

    healthcheck:
      test: [ "CMD-SHELL", "bash -c '</dev/tcp/localhost/7001'" ]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 30s

    environment:
      ADMIN_NAME: HospitalAuthAdminServer
      ADMIN_LISTEN_PORT: 7001
      ADMINISTRATION_PORT: 9002
      DOMAIN_NAME: hospital_auth_domain

    volumes:
      - weblogic_hospital_auth_data:/u01/oracle/user_projects/domains
      - ./domain.properties:/u01/oracle/properties/domain.properties:ro
      - ./deployment:/u01/deployment:ro
      # - ./datasource/postgresql-42.7.13.jar:/u01/oracle/wlserver/server/lib/postgresql-42.7.13.jar:ro

    depends_on:
      hospital_auth_db:
        condition: service_started
      weblogic_volume_init:
        condition: service_completed_successfully

  weblogic_datasource_init:
    image: container-registry.oracle.com/middleware/weblogic:14.1.1.0-11
    user: root
    volumes:
      - weblogic_hospital_auth_data:/u01/oracle/user_projects/domains
      - ./datasource/postgresql-42.7.13.jar:/u01/postgresql-42.7.13.jar:ro

    depends_on:
      weblogic:
        condition: service_healthy

    command:
      - bash
      - -c
      - |
        set -e

        DOMAIN_HOME=/u01/oracle/user_projects/domains/hospital_auth_domain
        DRIVER=/u01/postgresql-42.7.13.jar
        TARGET=$$DOMAIN_HOME/lib/postgresql-42.7.13.jar

        echo "========================================"
        echo "WebLogic datasource initialization"
        echo "========================================"

        echo "Checking domain..."
        ls -ld "$$DOMAIN_HOME"

        echo "Creating domain lib directory..."
        mkdir -p "$$DOMAIN_HOME/lib"

        echo "Copying PostgreSQL JDBC driver..."
        cp "$$DRIVER" "$$TARGET"

        echo "Setting ownership..."
        chown 1000:0 "$$TARGET"

        echo "Driver installed:"
        ls -lh "$$TARGET"

        echo "========================================"
        echo "Datasource initialization complete"
        echo "========================================"

  weblogic_restart:
    image: docker:cli

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    depends_on:
      weblogic_datasource_init:
        condition: service_completed_successfully

    command:
      - sh
      - -c
      - |
        set -e
        echo "========================================"
        echo "Restarting WebLogic"
        echo "========================================"

        docker restart weblogic-hospital-auth-server

        echo "Waiting for WebLogic to become healthy..."

        until [ "$$(docker inspect \
          --format='{{.State.Health.Status}}' \
          weblogic-hospital-auth-server)" = "healthy" ]; do

          sleep 5

          echo "Current status: $$(docker inspect \
            --format='{{.State.Health.Status}}' \
            weblogic-hospital-auth-server)"

        done

        echo "WebLogic is healthy."

        echo "========================================"
        echo "WebLogic restart complete"
        echo "========================================"

  weblogic_datasource_activation:
    image: container-registry.oracle.com/middleware/weblogic:14.1.1.0-11

    user: oracle

    volumes:
      - ./domain.properties:/u01/domain.properties:ro
      - ./datasource/database.properties:/u01/database.properties:ro
      - ./datasource/datasource.py:/u01/datasource/datasource.py:ro

    depends_on:
      weblogic_restart:
        condition: service_completed_successfully
      weblogic:
        condition: service_healthy

    entrypoint: /bin/bash

    command:
      - -c
      - |
        set -e

        echo "========================================"
        echo "WebLogic datasource activation starting"
        echo "========================================"

        echo "WLST directory:"
        ls -la /u01/datasource

        echo "Running WLST..."

        export USER_MEM_ARGS="-Dweblogic.security.TrustKeyStore=DemoTrust -Dweblogic.security.SSL.ignoreHostnameVerification=true"

        /u01/oracle/wlserver/common/bin/wlst.sh \
          /u01/datasource/datasource.py

        echo "========================================"
        echo "WebLogic datasource activation finished"
        echo "========================================"

  weblogic_deployer:
    image: container-registry.oracle.com/middleware/weblogic:14.1.1.0-11

    user: oracle

    volumes:
      - ./deployment:/u01/deployment:ro
      - ./domain.properties:/u01/domain.properties:ro
      - ./datasource/database.properties:/u01/database.properties:ro

    depends_on:
      weblogic_datasource_activation:
        condition: service_completed_successfully

    entrypoint: /bin/bash

    command:
      - -c
      - |
        set -e

        echo "========================================"
        echo "WebLogic deployer starting"
        echo "========================================"

        echo "Deployment directory:"
        ls -la /u01/deployment

        echo "Running WLST..."

        export USER_MEM_ARGS="-Dweblogic.security.TrustKeyStore=DemoTrust -Dweblogic.security.SSL.ignoreHostnameVerification=true"

        /u01/oracle/wlserver/common/bin/wlst.sh \
          /u01/deployment/deploy.py

        echo "========================================"
        echo "WebLogic deployer finished"
        echo "========================================"

  hospital_auth_db:
    build:
      context: .
      dockerfile: DockerFile

    container_name: hospital-auth-db

    environment:
      POSTGRES_DB: hospital_auth_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

    ports:
      - "5432:5432"

    volumes:
      - hospital_auth_db:/var/lib/postgresql/data

volumes:
  weblogic_hospital_auth_data:
  hospital_auth_db:
